In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('insurance.csv')

#CLEANING

In [4]:
df_cleaned = df.copy()

In [5]:
df_cleaned.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [6]:
df_cleaned.shape

(1338, 7)

In [7]:
df_cleaned.drop_duplicates(inplace=True)

In [8]:
df_cleaned.shape

(1337, 7)

In [9]:
df_cleaned.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [10]:
df_cleaned.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [11]:
df_cleaned['sex'].value_counts()

sex
male      675
female    662
Name: count, dtype: int64

In [12]:
df_cleaned['sex'] = df_cleaned['sex'].map({'male' : 0, 'female' : 1})

In [13]:
df_cleaned.head()

   age  sex     bmi  children smoker     region      charges
0   19    1  27.900         0    yes  southwest  16884.92400
1   18    0  33.770         1     no  southeast   1725.55230
2   28    0  33.000         3     no  southeast   4449.46200
3   33    0  22.705         0     no  northwest  21984.47061
4   32    0  28.880         0     no  northwest   3866.85520

In [14]:
df_cleaned['smoker'].value_counts()

smoker
no     1063
yes     274
Name: count, dtype: int64

In [15]:
df_cleaned['smoker'] = df_cleaned['smoker'].map({'yes' : 1, 'no' : 0})

In [16]:

df_cleaned.head()

   age  sex     bmi  children  smoker     region      charges
0   19    1  27.900         0       1  southwest  16884.92400
1   18    0  33.770         1       0  southeast   1725.55230
2   28    0  33.000         3       0  southeast   4449.46200
3   33    0  22.705         0       0  northwest  21984.47061
4   32    0  28.880         0       0  northwest   3866.85520

In [17]:
df_cleaned.rename(columns = {'sex' : 'ismale', 'smoker' : 'issmoker'},inplace = True)

In [18]:
df_cleaned.head()

   age  ismale     bmi  children  issmoker     region      charges
0   19       1  27.900         0         1  southwest  16884.92400
1   18       0  33.770         1         0  southeast   1725.55230
2   28       0  33.000         3         0  southeast   4449.46200
3   33       0  22.705         0         0  northwest  21984.47061
4   32       0  28.880         0         0  northwest   3866.85520

In [19]:
df_cleaned['region'].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

In [21]:
df_cleaned = pd.get_dummies(df_cleaned, columns=['region'], drop_first=True)

In [22]:
df_cleaned.head()

,age,ismale,bmi,children,issmoker,charges,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,16884.92400,False,False,True
1,18,0,33.770,1,0,1725.55230,False,True,False
2,28,0,33.000,3,0,4449.46200,False,True,False
3,33,0,22.705,0,0,21984.47061,True,False,False
4,32,0,28.880,0,0,3866.85520,True,False,False

In [23]:
df_cleaned = df_cleaned.astype(int)

In [25]:
df_cleaned

,age,ismale,bmi,children,issmoker,charges,region_northwest,region_southeast,region_southwest
0,19,1,27,0,1,16884,0,0,1
1,18,0,33,1,0,1725,0,1,0
2,28,0,33,3,0,4449,0,1,0
3,33,0,22,0,0,21984,1,0,0
4,32,0,28,0,0,3866,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,0,30,3,0,10600,1,0,0
1334,18,1,31,0,0,2205,0,0,0
1335,18,1,36,0,0,1629,0,1,0
1336,21,1,25,0,0,2007,0,0,1
1337,61,1,29,0,1,29141,1,0,0